# Generated by Django 6.0 on 2025-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GG", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelancerSignin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=50)),
                ("skills", models.CharField(max_length=255)),
                ("experience", models.FloatField()),
                ("location", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("profile_description", models.TextField()),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
